Repository DecodersCommunity/dsa-library, pull requests merged in 2022-10, with the labels that each got.

#1 Added first unique character program
  Data Structures/String/first_unique_character.cpp
Labels: hacktoberfest-accepted

#4 added bubblesort in c++
  Algorithms/bubblesort_c++.cpp
Labels: hacktoberfest-accepted

#3 Added selection Sort algorithm (c++)
  Algorithms/selectionsort_c++.cpp
  Data Structures/Queue/Queue_c++.cpp
Labels: hacktoberfest-accepted

#2 Created a java program to store elements in array
  Data Structures/Array/arraycontainer_java.java
  Data Structures/String/skipcharacter_java.java
Labels: hacktoberfest-accepted

#14 #12 Added queue implementation in python
  Data Structures/Queue/queue.py
Labels: good first issue, hacktoberfest-accepted

#18 Hacktoberfest2022
  Algorithms/BubbleSort/bubble_sort.c
  Data Structures/Linked List/linked_list_deletion.c
  Data Structures/Linked List/linked_list_insertion.c
Labels: good first issue, hacktoberfest-accepted

#21 #12 Added stack implementation in Python
  Data Structures/Stack/stack.py
Labels: good first issue, hacktoberfest-accepted

#17 Implemented count sort in C++
  Algorithms/CountSort/countsort.cpp
Labels: good first issue, hacktoberfest-accepted

#6 count-and-sum-of-nodes-in-binary-tree
  Data Structures/Tree/count-and-sum-of-nodes-in-binary-tree.cpp
Labels: hacktoberfest-accepted

#15 Added Binary Search C++ Algorithm.
  Algorithms/binarysearch/binarysearch.cpp
Labels: good first issue, hacktoberfest-accepted

#8 Added MergeSort in C++, Python, Java #5
  Algorithms/MergeSort/mergesort.cpp
  Algorithms/MergeSort/mergesort.java
  Algorithms/MergeSort/mergesort.py
Labels: good first issue, hacktoberfest-accepted

#10 Added linearsearch in c++
  Algorithms/LinearSearch/linearsearch.cpp
Labels: good first issue, hacktoberfest-accepted

#33 Added Balanced Binary tree algorithm
  Data Structures/Binary Search Tree/BalancedBinaryTree.cpp
Labels: good first issue, hacktoberfest-accepted

#11 Added stack in C++
  Data Structures/Stack/stack.cpp
Labels: good first issue, hacktoberfest-accepted

#23 added kadane's algo and dijkstra's algo
  Algorithms/dijkstras/dijkstras.cpp
  Algorithms/kadane/kadane.cpp
Labels: good first issue, hacktoberfest-accepted

#26 #12 Added Binary Search Tree Implementation in C++
  Data Structures/Binary Search Tree/binarySearchTree.cpp
Labels: good first issue, hacktoberfest-accepted

#35 Created stack using java
  Data Structures/Stack/stack.java
Labels: good first issue, hacktoberfest-accepted

#37 Added dp folder
  Algorithms/dp/01knapsack.cpp
  Algorithms/dp/countSubsets.cpp
  Algorithms/dp/fib.cpp
  Algorithms/dp/ladders.cpp
  Algorithms/dp/lcs.cpp
  Algorithms/dp/longestCommonSubstring.cpp
  Algorithms/dp/longestPalindromicSubseq.cpp
  Algorithms/dp/longestRepeatingSubseq.cpp
  Algorithms/dp/maxWaysCoinChange.cpp
  Algorithms/dp/mcm.cpp
  Algorithms/dp/minCoinChange.cpp
  Algorithms/dp/minNumOfInsAndDel.cpp
  Algorithms/dp/minStepsTo1.cpp
  Algorithms/dp/palindromePartition.cpp
  Algorithms/dp/printLCS.cpp
  Algorithms/dp/printSCS.cpp
  Algorithms/dp/rodCutting.cpp
  Algorithms/dp/shortestCommonSuperseq.cpp
  Algorithms/dp/subsetSumTarget.cpp
  Algorithms/dp/unboundedKnapsack.cpp
  Algorithms/dp/uniquePaths.cpp
  Algorithms/dp/wines.cpp
Labels: hacktoberfest-accepted

#38 Insertion in Doubly Linked List
  Data Structures/Linked List/DoublyLinkedlist.cpp
Labels: good first issue, hacktoberfest-accepted

#28 Quick Sort added
  Algorithms/QuickSort/QuickSort.cpp
Labels: good first issue, hacktoberfest-accepted

#40 Updated algorithm folder with sieve of eratosthenes algorithm
  Algorithms/SieveofEratosthenes/Sieve_of_Eratosthenes.cpp
Labels: good first issue, hacktoberfest-accepted

#44 Check Anagrams
  Data Structures/String/anagram.cpp
Labels: good first issue, hacktoberfest-accepted

#56 Added Interploation Search In C
  Algorithms/Interpolation Search/interpolationsearch.c
Labels: good first issue, hacktoberfest-accepted

#70 added palindrome.cpp
  Data Structures/String/palindrome.cpp
Labels: good first issue, hacktoberfest-accepted

#71 Create Dlinkedlistdeletion.cpp
  Data Structures/Linked List/Dlinkedlistdeletion.cpp
Labels: good first issue, hacktoberfest-accepted

#72 Create bfs.cpp
  Algorithms/BFS/bfs.cpp
Labels: good first issue, hacktoberfest-accepted

#73 Create dfs.cpp
  Algorithms/DFS/dfs.cpp
Labels: good first issue, hacktoberfest-accepted

#74 Create DoublyLinkedlist.C
  Data Structures/Linked List/DoublyLinkedlist.c
Labels: good first issue, hacktoberfest-accepted

#69 Create stack.cpp
  Algorithms/insertion sort.cpp
  Data Structures/Linked List/stack.cpp
Labels: good first issue, hacktoberfest-accepted

#77 Stack
  Data Structures/Stack/README.md
Labels: good first issue, hacktoberfest-accepted

#80 Added String Description
  Data Structures/String/README.md
Labels: good first issue, hacktoberfest-accepted

#78 Added Array Description
  Data Structures/Array/README.md
Labels: good first issue, hacktoberfest-accepted

#81 Added Queue Data Structure Description
  Data Structures/Queue/README.md
Labels: good first issue, hacktoberfest-accepted

#63 Create bogosort.py
  Algorithms/BogoSort/bogosort.py
  Algorithms/BubbleSort/bubblesort.c
  Algorithms/BubbleSort/bubblesort.cpp
  Algorithms/InterpolationSearch/interpolationsearch.c
Labels: good first issue, hacktoberfest-accepted

#34 Quick sort algorithm
  Algorithms/Hashing/count_frequency.cpp
  Algorithms/QuickSort/quicksort.cpp
  Data Structures/Graph/BFS_c++.cpp
  Data Structures/Hashing/Count_frequency.cpp
  Data Structures/Sorting/Bubble_sort.cpp
Labels: good first issue, hacktoberfest-accepted

#79 Create arrlen.cpp
  Data Structures/Array/arrlen.cpp
  Data Structures/String/revstring.cpp
Labels: good first issue, hacktoberfest-accepted

#76 Traversalofanarray_C.c
  Data Structures/Array/Traversalofanarray_C.c
Labels: hacktoberfest-accepted

#84 Tower of Hanoi added
  Algorithms/Tower_of_Hanoi_java.java
Labels: hacktoberfest-accepted

#83 added bfs and dfs in proper folder
  Algorithms/Graph Search/bfs.cpp
  Algorithms/Graph Search/dfs.cpp
Labels: hacktoberfest-accepted

#82 I have changed the folder name under which it should actually be included
  Algorithms/Divide_and_Conquer/closest_pair_algorithm.cpp
Labels: hacktoberfest-accepted

#65 Added ArrayRotation_c++.cpp
  Data Structures/Array/ArrayRotation_c++.cpp
Labels: hacktoberfest-accepted

#64 Added TimSort
  Algorithms/timesort.cpp
Labels: hacktoberfest-accepted

#85 Create CocktailSort.cpp
  Data Structures/Sorting/CocktailSort.cpp
Labels: hacktoberfest-accepted

#67 Added Sieve of Eratosthenes in JAVA
  Algorithms/SieveofEratosthenes/SieveOfEratosthenes.java
Labels: hacktoberfest-accepted

#62 HeapSort_cpp.cpp created
  Algorithms/BinarySearch/BinarySearch_cpp.cpp
  Algorithms/HeapSort/HeapSort_cpp.cpp
  Algorithms/RadixSort/RadixSort_cpp.cpp
Labels: Awsome, hacktoberfest-accepted

#61 Create create_linked_list.c
  Data Structures/Linked List/create_linked_list.c
Labels: hacktoberfest-accepted

#68 created Extended Euclidian Algorithm
  Algorithms/euclidianAndExtendedEulidianGCD/euclidianAndExtendedEulidianGCD.cpp
  Data Structures/Tree/BSTimple.cpp
Labels: hacktoberfest-accepted

#58 added backtracking , heap and graph implementations in cpp
  Algorithms/backtracking/nqueen.cpp
  Algorithms/backtracking/ratinamaze.cpp
  Data Structures/Graph/graph.cpp
  Data Structures/Heap/heap.cpp
Labels: hacktoberfest-accepted

#54 Hashmap implementation added
  Data Structures/Hashmap/Hashmap.cpp
Labels: hacktoberfest-accepted

#57 Create Convert a given Binary Tree to Doubly Linked List_java.java
  Data Structures/Binary Search Tree/Convert a given Binary Tree to Doubly Linked List_java.java
Labels: hacktoberfest-accepted

#86 Create circular_Linked_list.java
  Data Structures/Linked List/circular_Linked_list.java
Labels: hacktoberfest-accepted

#53 Create levelOrderTraversalSpiralForm.cpp
  levelOrderTraversalSpiralForm.cpp
Labels: hacktoberfest-accepted

#87 Added Jump Search algorithm
  Algorithms/Jump Search/JumpSearch_java.java
Labels: hacktoberfest-accepted

#52 Quick Sort
  Algorithms/InsertionSort/InsertionSort.java
  Data Structures/QuickSort.java
Labels: hacktoberfest-accepted

#51 Updated Selection Sort and Merge Sort
  Algorithms/MergeSort/mergesort.c
  Algorithms/SelectionSort/selectionsort.c
Labels: hacktoberfest-accepted

#46 added rabin karp algorithm
  Algorithms/RabinKarpPatternSearch/rabinkarp.cpp
Labels: hacktoberfest-accepted

#48 added wavesort algorithm
  Algorithms/wavesort/wavesort/wavesort_python.py
  Algorithms/wavesort/wavesort_c++.cpp
Labels: hacktoberfest-accepted

#30 Create balancedBinarySearchTree.cpp
  Data Structures/Binary Search Tree/balancedBinarySearchTree.cpp
Labels: hacktoberfest-accepted

#88 Create SieveofEratosthenes.cpp
  Data Structures/Bit_manipulation/SieveofEratosthenes.cpp
Labels: hacktoberfest-accepted

#92 Added greedy algos folder
  Algorithms/greedy/Defence_of_a_kingdom.cpp
  Algorithms/greedy/I_AM_VERY_BUSY.cpp
  Algorithms/greedy/LoadBalancing.cpp
  Algorithms/greedy/NMeetingInRoom.cpp
  Algorithms/greedy/baised.cpp
  Algorithms/greedy/chopsticksCodechef.cpp
  Algorithms/greedy/jobSeq.cpp
  Algorithms/greedy/minPlatforms.cpp
Labels: hacktoberfest-accepted

#101 Added Array Description
  Data Structures/Array/README.md
Labels: documentation, hacktoberfest-accepted

#102 Added Stack
  Data Structures/Stack/README.md
Labels: documentation, hacktoberfest-accepted

#103 Added queue Description
  Data Structures/Queue/README.md
Labels: documentation, hacktoberfest-accepted

#104 Added String Description
  Data Structures/String/README.md
Labels: documentation, hacktoberfest-accepted

#16 Created Linked List.cpp
  Algorithms/topologicalsearch/topologicalsearch.cpp
  Data Structures/Linked List/linkedlist.cpp
Labels: good first issue, hacktoberfest-accepted

#45 Update README.md
  Data Structures/Tree/README.md
  Data Structures/Tree/tree.cpp
Labels: good first issue, hacktoberfest-accepted

#49 MinHeap implementation using ArrayList in Java
  Data Structures/Heap/README.md
  Data Structures/Heap/minheap_java.java
  Data Structures/String/skipcharacter_java.java
Labels: good first issue, hacktoberfest-accepted

#47 Added Heapsort Algorithm and Huffman Tree
  Algorithms/HeapSort/heapsort.c
  Algorithms/HeapSort/heapsort.cpp
  Algorithms/HeapSort/heapsort.java
  Data Structures/Tree/huffmantree.cpp
Labels: good first issue, hacktoberfest-accepted

#91 Create HashTable.md
  Data Structures/Hashing/HashTable.md
Labels: documentation, hacktoberfest-accepted

#108 Maintained a systematic file structure
  Algorithms/InsertionSort/insertion sort.cpp
  Algorithms/QuickSort/QuickSort.java
  Algorithms/TimeSort/timesort.cpp
  Algorithms/TowerOfHanoi/Tower_of_Hanoi.java
  Algorithms/dp/levelOrderTraversalSpiralForm.cpp
  Algorithms/wavesort/wavesort_python.py
Labels: special, hacktoberfest-accepted

#99 Create array_multiplication.cpp
  Data Structures/Array/arraymultiplication.cpp
Labels: good first issue, hacktoberfest-accepted

#110 Added tree documentation
  Data Structures/Tree/README.md
Labels: documentation, hacktoberfest-accepted

#111 Added hashmap documentation
  Data Structures/Hashmap/README.md
Labels: good first issue, hacktoberfest-accepted

#112 Added graph documentation
  Data Structures/Graph/README.md
Labels: documentation, hacktoberfest-accepted

#114 Folders rearranged
  Data Structures/Hashmap/Count_frequency.cpp
  Data Structures/Hashmap/HashTable.md
Labels: enhancement, special, hacktoberfest-accepted

#113 Added Dequeue Documentation
  Data Structures/Dequeue/README.md
Labels: documentation, hacktoberfest-accepted

#115 Dequeue code added
  Data Structures/Dequeue/dequeue.cpp
Labels: good first issue, hacktoberfest-accepted

#116 Added dequeue.py
  Data Structures/Dequeue/dequeue.py
Labels: good first issue, hacktoberfest-accepted

#118 Create prim's.cpp
  Data Structures/Graph/prim's.cpp
Labels: good first issue, hacktoberfest-accepted

#123 Create LCMofgivenarrayelement.cpp
  Data Structures/Array/LCMofgivenarrayelement.cpp
Labels: good first issue, hacktoberfest-accepted

#126 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#119 Create kruskal's theorem
  Algorithms/Pollard’s_Rho/Pollard’s_Rho.cpp
  Algorithms/SieveofEratosthenes/SieveofEratosthenes.java
  Data Structures/Graph/kruskal's theorem.cpp
Labels: good first issue, hacktoberfest-accepted

#128 Create LowestCommonAncestorinaBinaryTree
  Data Structures/Binary Search Tree/LowestCommonAncestorinaBinaryTree.cpp
Labels: good first issue, hacktoberfest-accepted

#129 Create CheckifanumberisPalindrome
  Data Structures/Hashmap/HashMapinJavawithExample.java
  Data Structures/String/CheckifanumberisPalindrome.cpp
Labels: good first issue, hacktoberfest-accepted

#24 Searching for an element in a linked list C++
  Data Structures/Linked List/linked list search.cpp
Labels: good first issue, hacktoberfest-accepted

#137 Shell Sort implementation in C++
  Algorithms/ShellSort/ShellSort.cpp
Labels: good first issue, hacktoberfest-accepted

#167 linked list node class added
  Data Structures/Linked List/mid_node.cpp
  Data Structures/Linked List/node.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#172 graph node added
  Data Structures/Graph/node.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#138 please merge it
  Algorithms/EvenOdd/evenodd.cpp
Labels: good first issue, hacktoberfest-accepted

#143 Circular Linked List : Menu Driven program
  Data Structures/Linked List/CircularLinkedList.cpp
  Data Structures/Linked List/SinglyLinkedList.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#173 treenode added
  Data Structures/Tree/node.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#152 BogoSort in cpp
  Algorithms/BogoSort/BogoSort.cpp
Labels: good first issue, hacktoberfest-accepted

#174 easy_input added
  Data Structures/Tree/easyinp.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#135 Matrix Chain Multiplication implementation in C
  Algorithms/dp/matrixchainmultiplication.c
Labels: hacktoberfest-accepted

#176 Solved Bellman Ford Algorithm
  Algorithms/Bellman Ford Algorithm/BellmanFordAlgorithm.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#175 Added a program to find median of two sorted Array
  Data Structures/Array/Median of Two Sorted Arrays.java
Labels: hacktoberfest-accepted

#171 String Hashing added
  Algorithms/Hashing/StringHashing.cpp
  Data Structures/Bit_manipulation/checkPowerOf2.cpp
Labels: hacktoberfest-accepted

#36 Update README.md
  README.md
Labels: hacktoberfest-accepted

#170 Inorder Traversal of Binary tree
  Data Structures/Binary Search Tree/BST iterator.cpp
  Data Structures/Tree/Inorder Traversal of Binary Tree.cpp
Labels: hacktoberfest-accepted

#166 Added array rotate in cpp
  Data Structures/Array/array_rotate.cpp
Labels: hacktoberfest-accepted

#165 Added dequeue.java
  Data Structures/Dequeue/dequeue.java
Labels: hacktoberfest-accepted

#164 Create coinChanging.java
  Data Structures/Array/coinChanging.java
Labels: hacktoberfest-accepted

#163 Create Binary Tree
  Data Structures/Binary Tree
Labels: hacktoberfest-accepted

#162 Create mergeList.cpp
  Data Structures/Linked List/mergeList.cpp
Labels: hacktoberfest-accepted

#161 Binary Search implementation in Java
  Algorithms/BinarySearch/BinarySearch.java
Labels: hacktoberfest-accepted

#158 Kahn's Algorithm
  Algorithms/backtracking/Sudoku_solver.cpp
  Algorithms/kahn's Algorithm/Kahns_algorithm.cpp
  Algorithms/kahn's Algorithm/Kahns_algorithm.exe
Labels: hacktoberfest-accepted

#157 TimeSort.java
  Algorithms/ShellSort/ShellSort.py
  Algorithms/TimeSort/TimeSort.py
Labels: hacktoberfest-accepted

#149 Count Sort in c
  Algorithms/BinarySearch/BinarySearch.c
  Algorithms/CountSort/CountSort.c
Labels: hacktoberfest-accepted

#145 Added SearchBST in Data Structures
  Data Structures/Tree/searchBst.cpp
Labels: hacktoberfest-accepted

#144 Added DNF sort
  Algorithms/DNFsort/DNFsort_c++.cpp
Labels: hacktoberfest-accepted

#142 added deletion of files
  Search-Destroy.cpp
Labels: hacktoberfest-accepted

#140 Added the pigeon hole sort
  Algorithms/PigeonHole/pigeonhole_java.java
Labels: hacktoberfest-accepted

#139 Create array_merge.c
  Data Structures/Array/array_merge.c
Labels: hacktoberfest-accepted

#136 Added square root using binary search
  Algorithms/BinarySearch/squarerootusingbinarysearch.cpp
Labels: hacktoberfest-accepted

#134 Transpose-a-matrix and pre,post,inorder traversel in a tree
  Algorithms/tree-traversal/inorderTraversal$Node.class
  Algorithms/tree-traversal/inorderTraversal.class
  Algorithms/tree-traversal/inorderTraversal.java
  Algorithms/tree-traversal/postorderTraversal$Node.class
  Algorithms/tree-traversal/postorderTraversal.class
  Algorithms/tree-traversal/postorderTraversal.java
  Algorithms/tree-traversal/preorderTraversal$Node.class
  Algorithms/tree-traversal/preorderTraversal.class
  Algorithms/tree-traversal/preorderTraversal.java
  Data Structures/Array/transposeofmatrixjava.class
  Data Structures/Array/transposeofmatrixjava.java
Labels: hacktoberfest-accepted

#133 Added linearsearch.java
  Algorithms/LinearSearch/linearsearch.java
  Algorithms/MooreVotingAlgorithm/moorevotingalgorithm.java
Labels: hacktoberfest-accepted

#132 Added StringConcatenation_c++.cpp
  Data Structures/String/StringConcatenation_c++.cpp
Labels: hacktoberfest-accepted

#130 Added some problems in Array using cpp
  Data Structures/Array/AlternateSwap.cpp
  Data Structures/Array/reverse.cpp
  Data Structures/Array/sum_of_elements_Array.cpp
Labels: hacktoberfest-accepted

#127 Rotate matrix elements clockwise
  Data Structures/Array/Rotate_matrix_elements_clockwise.cpp
Labels: hacktoberfest-accepted

#121 Create SubArray.cpp
  Data Structures/Array/SubArray.cpp
Labels: hacktoberfest-accepted

#117 Added Insertion Sort Code in C
  Algorithms/InsertionSort/InsertionSort.c
Labels: hacktoberfest-accepted

#106 added fenwick tree (binary indexed tree)
  Data Structures/Tree/Fenwick tree(Binary indexed Tree)
Labels: hacktoberfest-accepted

#105 Bellman ford algo in cpp added
  Algorithms/Bellman Ford/bellman_ford.cpp
  Algorithms/Bellman Ford/bellman_ford.exe
Labels: hacktoberfest-accepted

#100 added circular queue implementations
  Data Structures/Queue/CircularQueue/README.md
  Data Structures/Queue/CircularQueue/circularqueue.cpp
  Data Structures/Queue/CircularQueue/circularqueue_using_array.cpp
  Data Structures/Queue/CircularQueue/circularqueue_using_linkedlist.cpp
  Data Structures/Queue/queue_using_linkedlist.cpp
  Data Structures/Queue/queue_using_stack.cpp
Labels: hacktoberfest-accepted

#97 Added ArrayRearrangement_c++.cpp
  Data Structures/Array/ArrayRearrangement_c++.cpp
Labels: hacktoberfest-accepted

#90 Added 4 Python Algorithms
  Algorithms/BinarySearch/binary_search.py
  Algorithms/BubbleSort/Bubble Sorting.py
  Algorithms/InsertionSort/Insertion Sort.py
  Algorithms/LinearSearch/linear_search.py
Labels: hacktoberfest-accepted

#187 Added Selection Sort in Python
  Algorithms/SelectionSort/selectionsort.py
Labels: hacktoberfest-accepted

#188 Create 01Knapsack.py
  Algorithms/01Knapsack.py
Labels: hacktoberfest-accepted

#189 Added Heapsort in Python
  Algorithms/HeapSort/HeapSort.py
Labels: hacktoberfest-accepted

#197 Create lcs.py
  Algorithms/dp/lcs.py
Labels: hacktoberfest-accepted

#198 Create djikstras.py
  Algorithms/dijkstras/djikstras.py
Labels: hacktoberfest-accepted

#217 check if binary tree is a heap or not
  Data Structures/Heap/check if binary tree is a heap
Labels: hacktoberfest-accepted

#218 created k-ary heap
  Data Structures/Heap/k-ary heap
Labels: hacktoberfest-accepted

#219 dequeue implementation in java
  Data Structures/Dequeue/dequeue implementation in java
Labels: hacktoberfest-accepted

#220 Count strings with consecutive 1's
  Data Structures/String/Count strings with consecutive 1's
Labels: hacktoberfest-accepted

#216 create_binary_search_in_rotated_array.cpp file
  Algorithms/BinarySearch/binary_search_in_rotated_array.cpp
Labels: hacktoberfest-accepted

#212 cycle sort in c#
  Algorithms/CycleSort/cycleSort.cpp
  Algorithms/CycleSort/cycleSort.cs
Labels: hacktoberfest-accepted

#221 Create tim_sort.cpp
  Algorithms/tim_sort.cpp
Labels: hacktoberfest-accepted

#208 bubble sort js file added
  Algorithms/BubbleSort/bubbleSort.js
  Algorithms/CountSort/countSort.java
Labels: hacktoberfest-accepted

#224 Create BellmanFord.py
  Algorithms/Bellman Ford Algorithm/BellmanFord.py
Labels: hacktoberfest-accepted

#225 Create dnf.py
  Algorithms/DNFsort/dnf.py
Labels: hacktoberfest-accepted

#226 Create rabinkarp.py
  Algorithms/RabinKarpPatternSearch/rabinkarp.py
Labels: hacktoberfest-accepted

#227 Create pigeonhole.py
  Algorithms/PigeonHole/pigeonhole.py
Labels: hacktoberfest-accepted

#241 Create continuoustree
  Data Structures/Queue/levelorderbinarytreetraversal.cpp
  Data Structures/continuoustree.cpp
Labels: hacktoberfest-accepted

#242 Added
  Data Structures/Array/sortthegivenmatrix
  Data Structures/heapsort
  Data Structures/thestockspanproblem
Labels: good first issue, hacktoberfest-accepted

#251 Create moveallzeroestoendofarray
  moveallzeroestoendofarray.cpp
Labels: good first issue, hacktoberfest-accepted
